Repository hongseongkim/SpartaHubFlow, pull requests merged in 2024-09, with the labels that each got.

#6 Eureka server 초기 설정 및 구성
  eureka-server/.gitignore
  eureka-server/build.gradle
  eureka-server/gradle/wrapper/gradle-wrapper.properties
  eureka-server/gradlew
  eureka-server/gradlew.bat
  eureka-server/settings.gradle
  eureka-server/src/main/java/com/spata/eurekaserver/EurekaServerApplication.java
  eureka-server/src/main/resources/application.yml
  eureka-server/src/test/java/com/spata/eurekaserver/EurekaServerApplicationTests.java
Labels: implementation

#7 Product 도메인 기본 기능 구현
  com.sparta.hotsix.product/build.gradle
  com.sparta.hotsix.product/src/main/java/com/sparta/hotsix/product/ProductApplication.java
  com.sparta.hotsix.product/src/main/java/com/sparta/hotsix/product/client/CompanyClient.java
  com.sparta.hotsix.product/src/main/java/com/sparta/hotsix/product/client/HubClient.java
  com.sparta.hotsix.product/src/main/java/com/sparta/hotsix/product/client/UserClient.java
  com.sparta.hotsix.product/src/main/java/com/sparta/hotsix/product/controller/ProductController.java
  com.sparta.hotsix.product/src/main/java/com/sparta/hotsix/product/domain/dto/CompanyDto.java
  com.sparta.hotsix.product/src/main/java/com/sparta/hotsix/product/domain/dto/HubDto.java
  com.sparta.hotsix.product/src/main/java/com/sparta/hotsix/product/domain/dto/ProductDto.java
  com.sparta.hotsix.product/src/main/java/com/sparta/hotsix/product/domain/dto/UserDto.java
  com.sparta.hotsix.product/src/main/java/com/sparta/hotsix/product/domain/entity/Product.java
  com.sparta.hotsix.product/src/main/java/com/sparta/hotsix/product/domain/entity/Timestamped.java
  com.sparta.hotsix.product/src/main/java/com/sparta/hotsix/product/repository/ProductRepository.java
  com.sparta.hotsix.product/src/main/java/com/sparta/hotsix/product/service/ProductService.java
  com.sparta.hotsix.product/src/main/resources/application.yml
  com.sparta.hotsix.product/src/test/java/com/sparta/hotsix/product/ProductApplicationTests.java
Labels: implementation

#17 Company 도메인 기본 기능 구현
  company/.gitignore
  company/build.gradle
  company/src/main/java/com/sparta/company/CompanyApplication.java
  company/src/main/java/com/sparta/company/client/HubClient.java
  company/src/main/java/com/sparta/company/controller/CompanyController.java
  company/src/main/java/com/sparta/company/domain/dto/CompanyDto.java
  company/src/main/java/com/sparta/company/domain/dto/HubDto.java
  company/src/main/java/com/sparta/company/domain/entity/Company.java
  company/src/main/java/com/sparta/company/domain/entity/CompanyTypeEnum.java
  company/src/main/java/com/sparta/company/domain/entity/Timestamped.java
  company/src/main/java/com/sparta/company/repository/CompanyRepository.java
  company/src/main/java/com/sparta/company/service/CompanyService.java
  company/src/main/resources/application.yml
  company/src/test/java/com/sparta/company/CompanyApplicationTests.java
Labels: feature

#14 Hub, Map Application 구현
  eureka-server/.gitignore
  hub/build.gradle
  hub/src/main/java/com/sparta/hub/HubApplication.java
  hub/src/main/java/com/sparta/hub/application/dto/HubDto.java
  hub/src/main/java/com/sparta/hub/application/exception/ErrorCode.java
  hub/src/main/java/com/sparta/hub/application/exception/GlobalExceptionHandler.java
  hub/src/main/java/com/sparta/hub/application/exception/ServiceException.java
  hub/src/main/java/com/sparta/hub/application/service/AuthorizationService.java
  hub/src/main/java/com/sparta/hub/application/service/HubCacheService.java
  hub/src/main/java/com/sparta/hub/domain/model/Hub.java
  hub/src/main/java/com/sparta/hub/domain/repository/HubCustomRepository.java
  hub/src/main/java/com/sparta/hub/domain/service/HubService.java
  hub/src/main/java/com/sparta/hub/domain/service/HubServiceImpl.java
  hub/src/main/java/com/sparta/hub/infrastructure/client/MapServiceClient.java
  hub/src/main/java/com/sparta/hub/infrastructure/configuration/auditing/AuditAwareImpl.java
  hub/src/main/java/com/sparta/hub/infrastructure/configuration/auditing/listener/SoftDeleteListener.java
  hub/src/main/java/com/sparta/hub/infrastructure/configuration/cache/CacheConfig.java
  hub/src/main/java/com/sparta/hub/infrastructure/configuration/jpa/JpaConfig.java
  hub/src/main/java/com/sparta/hub/infrastructure/initializer/HubInitializer.java
  hub/src/main/java/com/sparta/hub/infrastructure/repository/HubRepository.java
  hub/src/main/java/com/sparta/hub/infrastructure/repository/HubRepositoryImpl.java
  hub/src/main/java/com/sparta/hub/presentation/controller/HubController.java
  hub/src/main/java/com/sparta/hub/presentation/dto/request/HubRequest.java
  hub/src/main/java/com/sparta/hub/presentation/dto/response/HubResponseDto.java
  hub/src/main/java/com/sparta/hub/presentation/dto/response/common/FailedResponseBody.java
  hub/src/main/java/com/sparta/hub/presentation/dto/response/common/ResponseBody.java
  hub/src/main/java/com/sparta/hub/presentation/dto/response/common/ResponseUtil.java
  hub/src/main/java/com/sparta/hub/presentation/dto/response/common/SuccessResponseBody.java
  hub/src/main/resources/application.yml
  hub/src/test/java/com/sparta/hub/HubApplicationTests.java
  map/build.gradle
  map/src/main/java/com/sparta/map/MapApplication.java
  map/src/main/java/com/sparta/map/application/service/MapApplicationService.java
  map/src/main/java/com/sparta/map/domain/model/Coordinates.java
  map/src/main/java/com/sparta/map/domain/repository/MapRepository.java
  map/src/main/java/com/sparta/map/infrastructure/api/GoogleMapsApiService.java
  map/src/main/java/com/sparta/map/presentation/controller/MapController.java
  map/src/main/java/com/sparta/map/presentation/dto/request/DirectionsRequest.java
  map/src/main/java/com/sparta/map/presentation/dto/response/DirectionsResponse.java
  map/src/main/resources/application.yml
  map/src/test/java/com/sparta/map/MapApplicationTests.java
Labels: implementation, feature

#22 Order, Product, Company App에 Swagger UI 적용 및 AI API 연동
  com.sparta.hotsix.product/build.gradle
  com.sparta.hotsix.product/src/main/java/com/sparta/hotsix/product/config/SwaggerConfig.java
  com.sparta.hotsix.product/src/main/java/com/sparta/hotsix/product/controller/AiChatController.java
  com.sparta.hotsix.product/src/main/java/com/sparta/hotsix/product/controller/ProductController.java
  com.sparta.hotsix.product/src/main/java/com/sparta/hotsix/product/domain/dto/AiChatDto.java
  com.sparta.hotsix.product/src/main/java/com/sparta/hotsix/product/domain/entity/ProductAiChat.java
  com.sparta.hotsix.product/src/main/java/com/sparta/hotsix/product/repository/AiChatRepository.java
  com.sparta.hotsix.product/src/main/java/com/sparta/hotsix/product/service/AiChatService.java
  com.sparta.hotsix.product/src/main/resources/application.yml
  company/build.gradle
  company/src/main/java/com/sparta/company/config/SwaggerConfig.java
  company/src/main/java/com/sparta/company/controller/AiChatController.java
  company/src/main/java/com/sparta/company/controller/CompanyController.java
  company/src/main/java/com/sparta/company/domain/dto/AiChatDto.java
  company/src/main/java/com/sparta/company/domain/entity/CompanyAiChat.java
  company/src/main/java/com/sparta/company/repository/AiChatRepository.java
  company/src/main/java/com/sparta/company/service/AiChatService.java
  company/src/main/resources/application.yml
  order/build.gradle
  order/src/main/java/com/sparta/order/config/SwaggerConfig.java
  order/src/main/java/com/sparta/order/controller/AiChatController.java
  order/src/main/java/com/sparta/order/controller/OrderController.java
  order/src/main/java/com/sparta/order/domain/dto/AiChatDto.java
  order/src/main/java/com/sparta/order/domain/entity/OrderAiChat.java
  order/src/main/java/com/sparta/order/repository/AiChatRepository.java
  order/src/main/java/com/sparta/order/service/AiChatService.java
  order/src/main/resources/application.yml
Labels: feature

#32 hub, delivery refacotring
  delivery/src/main/java/com/sparta/delivery/domain/delivery/controller/DeliveryController.java
  delivery/src/main/java/com/sparta/delivery/domain/delivery/controller/DeliveryPersonController.java
  delivery/src/main/java/com/sparta/delivery/domain/delivery/controller/DeliveryRouteController.java
  delivery/src/main/java/com/sparta/delivery/domain/delivery/controller/DeliveryStatusController.java
  delivery/src/main/java/com/sparta/delivery/domain/delivery/dto/DeliveryDto.java
  delivery/src/main/java/com/sparta/delivery/domain/delivery/dto/delivery/DeliveryDto.java
  delivery/src/main/java/com/sparta/delivery/domain/delivery/dto/delivery/DeliveryRequestDto.java
  delivery/src/main/java/com/sparta/delivery/domain/delivery/dto/delivery/DeliveryResponseDto.java
  delivery/src/main/java/com/sparta/delivery/domain/delivery/dto/hub/HubRouteResponseDto.java
  delivery/src/main/java/com/sparta/delivery/domain/delivery/dto/person/DeliveryPersonRequestDto.java
  delivery/src/main/java/com/sparta/delivery/domain/delivery/dto/route/DeliveryRouteDto.java
  delivery/src/main/java/com/sparta/delivery/domain/delivery/dto/route/DeliveryRouteRequestDto.java
  delivery/src/main/java/com/sparta/delivery/domain/delivery/model/Delivery.java
  delivery/src/main/java/com/sparta/delivery/domain/delivery/model/DeliveryPerson.java
  delivery/src/main/java/com/sparta/delivery/domain/delivery/model/DeliveryRoute.java
  delivery/src/main/java/com/sparta/delivery/domain/delivery/model/RouteSegment.java
  delivery/src/main/java/com/sparta/delivery/domain/delivery/model/enums/DeliveryPersonType.java
  delivery/src/main/java/com/sparta/delivery/domain/delivery/service/DeliveryPersonService.java
  delivery/src/main/java/com/sparta/delivery/domain/delivery/service/DeliveryRouteService.java
  delivery/src/main/java/com/sparta/delivery/domain/delivery/service/DeliveryService.java
  delivery/src/main/java/com/sparta/delivery/domain/delivery/service/DeliveryStatusService.java
  delivery/src/main/java/com/sparta/delivery/domain/route/domain/dto/DeliveryPersonRequestDto.java
  delivery/src/main/java/com/sparta/delivery/domain/route/domain/dto/DeliveryRouteDto.java
  delivery/src/main/java/com/sparta/delivery/domain/route/domain/dto/DeliveryRouteRequestDto.java
  delivery/src/main/java/com/sparta/delivery/infrastructure/client/HubFeignClient.java
  delivery/src/main/java/com/sparta/delivery/infrastructure/client/OrderFeignClient.java
  delivery/src/main/java/com/sparta/delivery/infrastructure/configuration/auditing/listener/SoftDeleteListener.java
  delivery/src/main/java/com/sparta/delivery/infrastructure/persistence/DeliveryRouteJpaRepository.java
  delivery/src/main/java/com/sparta/delivery/infrastructure/security/AuthorizationService.java
  hub/src/main/java/com/sparta/hub/application/initializer/HubInitializerService.java
  hub/src/main/java/com/sparta/hub/domain/hub/repository/HubCustomRepository.java
  hub/src/main/java/com/sparta/hub/domain/hub/service/HubServiceImpl.java
  hub/src/main/java/com/sparta/hub/domain/route/controller/HubRouteController.java
  hub/src/main/java/com/sparta/hub/domain/route/service/HubRouteService.java
  hub/src/main/java/com/sparta/hub/domain/route/service/cache/HubRouteCacheService.java
  hub/src/main/java/com/sparta/hub/domain/route/service/utils/RouteCalculationService.java
  hub/src/main/java/com/sparta/hub/domain/route/service/utils/RouteEstimator.java
  hub/src/main/java/com/sparta/hub/domain/route/service/utils/RouteEstimatorImpl.java
  hub/src/main/java/com/sparta/hub/domain/route/service/utils/RouteSegmentCalculator.java
  hub/src/main/java/com/sparta/hub/infrastructure/persistence/HubRepositoryImpl.java
Labels: refactoring
